apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-quarkus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-quarkus-app
  template:
    metadata:
      labels:
        app: my-quarkus-app
    spec:
      containers:
        - name: getting-started-jvm
          image: quay.io/ecrookshanks/getting-started-jvm 
          ports:
            - containerPort: 8080
