apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.containerPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect